installed ts and bun types
soul-workshop/domain pull request #23
Opened 2023-10-20 06:43 UTC by FredSteady23

2023-10-20 06:59 UTC, yaksh0nti requested changes

2023-10-20 06:59 UTC, yaksh0nti commented on package.json
> +    "typescript": "^5.2.2"
typescript в дев зависимость в продакшн сборке он не будет. Это чисто для нас разработчиков

2023-10-20 10:18 UTC, yaksh0nti approved these changes

2023-10-23 10:03 UTC, yaksh0nti requested changes

2023-10-23 10:03 UTC, yaksh0nti commented on package.json
измени зависимость от rilata2 от NurGeo на rilata2 из workshop

2023-10-23 11:43 UTC, xHetso approved these changes

2023-10-23 11:50 UTC, Renatter approved these changes

2023-10-24 06:35 UTC, closed without merging

2023-10-24 06:35 UTC, FredSteady23 commented
Уже слил в основную ветку