Feature/impl user repo
soul-workshop/domain pull request #47
Opened 2023-10-26 09:54 UTC by NurGeo

2023-10-27 10:57 UTC, FredSteady23 approved these changes

2023-10-27 11:47 UTC, yaksh0nti approved these changes

2023-11-02 12:24 UTC, yaksh0nti requested changes

2023-11-02 12:24 UTC, yaksh0nti commented on src/subject/infra/repository/user-json-impl.test.ts
> +      expect(notFoundCb).toThrow('not valid userId');
разве функцию не надо вызывать?

2023-11-02 12:24 UTC, yaksh0nti commented on src/subject/infra/repository/user-json-impl.test.ts
> +      expect(notFoundCb).toThrow('not valid userId');
тут telegramId: undefined а в ошибке написано 'not valid userId'

2023-11-02 17:00 UTC, NurGeo commented on src/subject/infra/repository/user-json-impl.test.ts
> +      expect(notFoundCb).toThrow('not valid userId');
нет, если на Throw

2023-11-02 17:06 UTC, NurGeo commented on src/subject/infra/repository/user-json-impl.test.ts
> +      expect(notFoundCb).toThrow('not valid userId');
а там нет реализации, потому что еще не был готов v-map, поэтому описание ошибки не правильно. Тому кто будет реализовывать этот функционал нужно будет написать правильно.

2023-11-02 17:06 UTC, NurGeo commented on src/subject/infra/repository/user-json-impl.test.ts
> +      const notValidTelegramId = getUserAttrs({ telegramId: ('5436134100' as unknown as number) });
потому что `telegramId: number`, но можно проверить на отрицательное число. Помоему Данияр добавил такое правил для этого поля.

2023-11-02 17:06 UTC, NurGeo commented on src/subject/infra/repository/user-json-impl.test.ts
> +      expect(notFoundCb).toThrow('not valid userId');
написал выше.

2023-11-03 06:12 UTC, yaksh0nti commented on src/subject/infra/repository/user-json-impl.test.ts
> +      expect(notFoundCb).toThrow('not valid userId');
прикольно не знал, считаю что вопрос решен

2023-11-03 06:17 UTC, yaksh0nti approved these changes

2023-11-03 06:17 UTC, yaksh0nti commented on src/subject/infra/repository/user-json-impl.test.ts
> +      expect(notFoundCb).toThrow('not valid userId');
я как полагаю мы не можем слить эту ветку пока не реализуем вмапы?

2023-11-08 05:59 UTC, yaksh0nti approved these changes

2023-11-09 16:54 UTC, yaksh0nti commented on src/subject/infra/repository/user-json-impl.ts
> +    });
Вообще не подумал что так можно). Спасибо, принял ваш вариант

2023-11-10 08:18 UTC, xHetso approved these changes

2023-11-15 09:40 UTC, closed without merging